apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: node-test-app
  namespace: node-test-app
  annotations:
    # Ingress class for AWS Load Balancer Controller
    kubernetes.io/ingress.class: "alb"
    # Configure ALB as internet-facing
    alb.ingress.kubernetes.io/scheme: internet-facing
    # Use IP as the target type for the Load Balancer
    alb.ingress.kubernetes.io/target-type: ip
    # Annotations for automatic TLS with Cert-Manager
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    # Configure automatic SSL redirection
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    alb.ingress.kubernetes.io/ssl-redirect: '443'

spec:
  rules:
    - host: node-test-app-{{ .Values.cluster_name }}.{{ .Values.domain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: node-test-app
                port:
                  number: 80
  tls:
    - hosts:
        - node-test-app-{{ .Values.cluster_name }}.{{ .Values.domain }}
      secretName: node-test-app-tls