apiVersion: v1
kind: Service
metadata:
  name: node-test-app
  namespace: node-test-app
spec:
  type: ClusterIP  # Change to NodePort or LoadBalancer if external access is needed
  selector:
    app: node-test-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000